name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Preparing Repositories
      uses: actions/checkout@v3
      with:
        token: '${{ secrets.ACCESS_TOKEN }}'
        submodules: recursive

    - name: make
      run: make
